language: java

services:
  - mysql

before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS pruebas_db;'
  - mysql -e 'USE pruebas_db;
              CREATE TABLE IF NOT EXISTS alumnos_tbl(
              id varchar(10) not null,
              nombre varchar(50) not null,
              email varchar(100) not null,
              edad int not null,
              constraint alumnos_tbl_pk
              primary key (ID)
              );'

addons:
  browserstack:
    username: "ottomontoya_w3vj9h"
    access_key: "tR9y6LGtyQjKzMwME1Sd"
  chrome: stable